docker-compose -f frontendweb/backend/docker-compose.yml up -d
docker-compose -f theory/numbers/numbers_server/docker-compose.yml up -d
docker-compose -f artificial_intelligence/Tic-T-AI-Toe/tictaitoe_server/docker-compose.yml up -d
docker-compose -f crypto/rsa_1/rsa_1_server/docker-compose.yml up -d
docker-compose -f crypto/rsa_2/rsa_2_server/docker-compose.yml up -d
docker-compose -f crypto/rsa_3/rsa_3_server/docker-compose.yml up -d
docker-compose -f relay-tracing/relay_tracing_server/docker-compose.yml up -d
docker-compose -f backendweb/qualifs-cs-2020-backendchecker/docker-compose.yml up -d
docker-compose -f ctf-track0/part0/docker-compose.yml up -d
docker-compose -f ctf-track0/part1/docker-compose.yml up -d
docker-compose -f ctf-track0/part2/docker-compose.yml up -d
docker-compose -f php_lfi/docker-compose.yml up -d